# -*- coding: utf-8 -*-
"""decision_tree_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mc9sF6N7P5ER9F0OCwrKOrbNEgUqIsN

#Decision Tree Regression

## import libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values # level
y = dataset.iloc[:, -1].values # salary

# Decision Tree Regression doesnt usually require feature scaling

print(X)

"""## Training the Decision Tree Regression model on the whole dataset"""

from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor()
regressor.fit(X, y)

"""##Predicting a new result"""

regressor.predict([[6.5]])

"""##Visualizing the decision tree regre4ssion results (higher resolution)"""

X_grid = np.arange(min(X), max(X), 0.01)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, color = 'red')
plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
plt.title('Truth or Bluff (Decision Tree Regression)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()